Pop-py/poppy-server

build.gradle, src/main/java/com/poppy/common/config/SecurityConfig.java, src/main/java/com/poppy/common/config/SwaggerConfig.java
=> [Docs]: Swagger 설정

src/main/java/com/poppy/common/entity/BaseTimeEntity.java
- BaseTimeEntity 생성
- 없음
- 없음
<br>
=> [Chore]: BaseTimeEntity 생성

src/main/java/com/poppy/common/entity/Images.java, src/main/java/com/poppy/common/entity/Token.java, src/main/java/com/poppy/domain/instagramReview/entity/InstagramReview.java, src/main/java/com/poppy/domain/likes/entity/Likes.java, src/main/java/com/poppy/domain/notification/entity/Notification.java, src/main/java/com/poppy/domain/notification/entity/NotificationStatus.java, src/main/java/com/poppy/domain/payment/entity/Payment.java, src/main/java/com/poppy/domain/payment/entity/PaymentStatus.java, src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java, src/main/java/com/poppy/domain/reservation/entity/Reservation.java, src/main/java/com/poppy/domain/reservation/entity/ReservationStatus.java, src/main/java/com/poppy/domain/review/entity/Review.java, src/main/java/com/poppy/domain/storeCategory/entity/StoreCategory.java, src/main/java/com/poppy/domain/user/entity/Role.java, src/main/java/com/poppy/domain/user/entity/User.java, src/main/java/com/poppy/domain/wishList/entity/WishList.java
=> [Feat]: Entity 구현

src/main/java/com/poppy/common/api/RspTemplate.java, src/main/java/com/poppy/common/exception/ApplicationException.java, src/main/java/com/poppy/common/exception/BusinessException.java, src/main/java/com/poppy/common/exception/ErrorCode.java, src/main/java/com/poppy/common/exception/dto/ErrorResponseDto.java, src/main/java/com/poppy/common/exception/handler/GlobalExceptionHandler.java, src/main/java/com/poppy/common/util/LoggingUtil.java
- 응답, 예외 템플릿 생성
- 여러 예외 상황에 대한 handler 작성, 응답 템플릿 작성
- 없음
<br>
=> [Feat]: 응답, 예외 템플릿 생성

src/main/java/com/poppy/common/config/security/SecurityConfig.java, src/main/java/com/poppy/domain/user/entity/User.java, src/main/java/com/poppy/domain/user/service/UserService.java
- 로그인 시 이메일 확인
- 없음
- nickname에서 unique 컬럼인 email로 수정
<br>
=> [Fix]: 로그인 시 이메일 확인

src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java
=> [Fix]: controller url 수정

src/main/java/com/poppy/domain/user/entity/User.java, src/main/java/com/poppy/domain/user/service/UserService.java
- 로그인 시 네이버 정보를 바탕으로 업데이트
- 없음
- User에 업데이트 메소드 생성
<br>
=> [Fix]: 로그인 시 네이버 정보를 바탕으로 업데이트

src/main/java/com/poppy/common/exception/ErrorCode.java, src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
=> [Refactor]: 날짜 범위 검색 예외 처리 추가

src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepositoryImpl.java, src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
=> [Refactor]: 카테고리별 조회 예외 처리 추가

build.gradle, src/main/java/com/poppy/common/auth/JwtTokenizer.java, src/main/java/com/poppy/common/auth/cache/OAuthOTUCache.java, src/main/java/com/poppy/common/auth/controller/OAuth2Controller.java, src/main/java/com/poppy/common/auth/handler/OAuth2LoginSuccessHandler.java, src/main/java/com/poppy/common/config/redis/RedisConfig.java, src/main/java/com/poppy/common/config/security/SecurityConfig.java
- 토큰 및 인증 코드 Redis에 저장
- RefreshToken을 통해 AccessToken 재발급 로직 추가
- RefreshToken, 인증 코드 Redis 저장
<br>
=> [Refactor]: 토큰 및 인증 코드 Redis에 저장

src/main/java/com/poppy/common/exception/ErrorCode.java, src/main/java/com/poppy/common/exception/handler/GlobalExceptionHandler.java, src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java, src/main/java/com/poppy/domain/reservation/controller/ReservationController.java, src/main/java/com/poppy/domain/reservation/dto/ReservationReqDto.java, src/main/java/com/poppy/domain/reservation/repository/ReservationRepository.java, src/main/java/com/poppy/domain/reservation/service/ReservationService.java
- 예약 관련 유효성, 예외 처리 추가
- 유효성 추가 (날짜 형식이 안 맞을 때, 파라미터 누락 등)
- 이미 해당 날짜에 예약이 있는 경우 예외 처리
- 없음
<br>
=> [Refactor]: 예약 관련 유효성, 예외 처리 추가

src/main/java/com/poppy/common/exception/ErrorCode.java, src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java, src/main/java/com/poppy/domain/popupStore/entity/ReservationType.java, src/main/java/com/poppy/domain/reservation/controller/ReservationController.java, src/main/java/com/poppy/domain/reservation/dto/ReservationReqDto.java, src/main/java/com/poppy/domain/reservation/dto/ReservationRspDto.java, src/main/java/com/poppy/domain/reservation/entity/Reservation.java, src/main/java/com/poppy/domain/reservation/entity/ReservationAvailableSlot.java, src/main/java/com/poppy/domain/reservation/repository/ReservationRepository.java, src/main/java/com/poppy/domain/reservation/service/RedisSlotService.java, src/main/java/com/poppy/domain/reservation/service/ReservationService.java, src/main/java/com/poppy/domain/user/controller/UserController.java, src/main/java/com/poppy/domain/user/dto/UserReservationRspDto.java, src/main/java/com/poppy/domain/user/entity/User.java, src/main/java/com/poppy/domain/user/repository/LoginUserProvider.java, src/main/java/com/poppy/domain/user/repository/LoginUserProviderImpl.java, src/main/java/com/poppy/domain/user/service/UserService.java, src/test/java/com/poppy/domain/reservation/service/ReservationServiceTest.java
- 예약 조회 및 삭제 구현
- 테스트 코드 작성
- 유저의 예약 내역 조회 구현
- 로그인 유저 확인 LoginUserProvider로 구분
- ReservationType으로 예약 유형 구분
<br>
=> [Feat]: 예약 조회 및 삭제 구현

src/main/java/com/poppy/admin/controller/AdminController.java, src/main/java/com/poppy/admin/service/AdminService.java, src/main/java/com/poppy/common/config/security/SecurityConfig.java, src/main/java/com/poppy/common/exception/ErrorCode.java, src/main/java/com/poppy/domain/popupStore/dto/request/PopupStoreReqDto.java, src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java, src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java, src/main/java/com/poppy/domain/storeCategory/repository/StoreCategoryRepository.java, src/main/java/com/poppy/domain/user/entity/Role.java, src/main/java/com/poppy/domain/user/entity/User.java
- 관리자 팝업스토어 등록 및 삭제 구현
- 없음 
- 없음
<br>
Closes #{이슈 번호}
=> [Feat]: 관리자 팝업스토어 등록 및 삭제 구현

src/main/java/com/poppy/admin/controller/AdminController.java, src/main/java/com/poppy/admin/service/AdminService.java, src/main/java/com/poppy/common/exception/ErrorCode.java, src/main/java/com/poppy/common/exception/handler/GlobalExceptionHandler.java, src/main/java/com/poppy/domain/popupStore/dto/request/PopupStoreReqDto.java, src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java, src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java, src/main/java/com/poppy/domain/reservation/repository/ReservationAvailableSlotCustomRepository.java, src/main/java/com/poppy/domain/reservation/repository/ReservationAvailableSlotCustomRepositoryImpl.java, src/main/java/com/poppy/domain/user/entity/User.java
- 팝업 스토어 등록 시 슬롯 분배 수정
- 휴무일 등록 로직 추가
- 휴무일을 제외하고 슬롯 분배하도록 수정
<br>
=> [Fix]: 팝업 스토어 등록 시 슬롯 분배 수정

src/main/java/com/poppy/common/exception/ErrorCode.java, src/main/java/com/poppy/domain/likes/entity/ReviewLike.java, src/main/java/com/poppy/domain/likes/repository/ReviewLikeRepository.java, src/main/java/com/poppy/domain/review/controller/ReviewController.java, src/main/java/com/poppy/domain/review/dto/request/ReviewReqDto.java, src/main/java/com/poppy/domain/review/dto/response/ReviewLikeRspDto.java, src/main/java/com/poppy/domain/review/dto/response/ReviewRspDto.java, src/main/java/com/poppy/domain/review/entity/Review.java, src/main/java/com/poppy/domain/review/repository/ReviewRepository.java, src/main/java/com/poppy/domain/review/service/ReviewService.java, src/main/java/com/poppy/domain/user/entity/User.java, src/test/java/com/poppy/domain/review/service/ReviewServiceTest.java
=> [Feat]: 리뷰 기능 및 좋아요

src/main/java/com/poppy/domain/review/ReviewSortType.java, src/main/java/com/poppy/domain/review/controller/ReviewController.java, src/main/java/com/poppy/domain/review/repository/ReviewRepository.java, src/main/java/com/poppy/domain/review/service/ReviewService.java, src/test/java/com/poppy/domain/review/service/ReviewServiceTest.java
- 리뷰 sort type 별 조회
- 없음 
- 없음
<br>
=> [Feat]: 리뷰 sort type 별 조회

src/main/java/com/poppy/common/exception/ErrorCode.java, src/main/java/com/poppy/domain/payment/service/PaymentService.java
- 결제 멱등성 보장 처리
- 결제 시 완료/취소 처리된 건지 확인
- 없음
<br>
=> [Refactor]: 결제 멱등성 보장 처리

.github/workflows/deploy.yml
- CI/CD 문서 수정
- Blue 서버와 Green 서버 최신화
- 없음
<br>
=> [Build]: CI/CD 문서 수정

src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java, src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java, src/main/java/com/poppy/domain/search/controller/SearchHistoryController.java, src/main/java/com/poppy/domain/search/service/SearchHistoryService.java, src/main/java/com/poppy/domain/search/service/StoreSearchService.java, src/main/java/com/poppy/domain/user/repository/LoginUserProviderImpl.java, src/test/java/com/poppy/domain/search/service/SearchHistoryServiceTest.java
- 검색어 저장, 조회, 삭제 구현
- 검색어 저장 Redis 이용
- 검색어 관련 테스트 코드 작성
- 이름으로 검색 시 로그인한 경우 검색어 저장
<br>
=> [Feat]: 검색어 저장, 조회, 삭제 구현

src/main/java/com/poppy/common/auth/controller/TestUserController.java, src/main/java/com/poppy/common/auth/handler/OAuth2LoginSuccessHandler.java, src/main/java/com/poppy/domain/user/controller/UserController.java, src/main/java/com/poppy/domain/user/dto/UpdateNicknameReqDto.java, src/main/java/com/poppy/domain/user/entity/User.java, src/main/java/com/poppy/domain/user/service/UserService.java
- 로그인 시 닉네임 설정, 핸드폰 번호 받기 추가
- 네이버 로그인 시 핸드폰 번호 추가로 받기
- 닉네임 변경 로직 추가
- 없음
<br>
=> [Feat]: 로그인 시 닉네임 설정, 핸드폰 번호 받기 추가

src/main/java/com/poppy/common/config/redis/NotificationPublisher.java, src/main/java/com/poppy/common/config/redis/NotificationSubscriber.java, src/main/java/com/poppy/common/config/security/SecurityConfig.java, src/main/java/com/poppy/domain/notification/controller/NotificationController.java, src/main/java/com/poppy/domain/notification/dto/NotificationDto.java, src/main/java/com/poppy/domain/notification/dto/ReservationNotificationDto.java, src/main/java/com/poppy/domain/notification/dto/WaitingNotificationDto.java, src/main/java/com/poppy/domain/notification/entity/Notification.java, src/main/java/com/poppy/domain/notification/entity/NotificationType.java, src/main/java/com/poppy/domain/notification/service/NotificationMessageGenerator.java, src/main/java/com/poppy/domain/notification/service/NotificationService.java, src/main/java/com/poppy/domain/payment/dto/ReservationPaymentRspDto.java, src/main/java/com/poppy/domain/reservation/dto/ReservationRspDto.java, src/main/java/com/poppy/domain/reservation/entity/ReservationStatus.java, src/main/java/com/poppy/domain/reservation/service/ReservationService.java, src/test/java/com/poppy/domain/notification/service/NotificationServiceTest.java, src/test/java/com/poppy/domain/reservation/service/ReservationServiceTest.java
- 예약 완료 후 알림 로직 구현
- 결제 및 예약이 완료되면 알림 전송
- 없음
<br>
=> [Feat]: 예약 완료 후 알림 로직 구현

src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java, src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java, src/main/java/com/poppy/domain/popupStore/entity/PopupStoreView.java, src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepository.java, src/main/java/com/poppy/domain/popupStore/repository/PopupStoreViewRepository.java, src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java, src/test/java/com/poppy/domain/popupstore/PopupStoreServiceTest.java
- 인기 팝업스토어 조회 로직 구현
- 카테고리 안에서의 인기 팝업스토어 조회
- 없음
<br>
- [ ✅  ] 💯 테스트는 잘 통과했나요?
- [ ✅  ] 🏗️ 빌드는 성공했나요?
- [ ✅  ] 🧹 불필요한 코드는 제거했나요?
- [ ✅  ] 💭 이슈는 등록했나요?
- [ ✅  ] 🏷️ 라벨은 등록했나요?
=> [Feat]: 인기 팝업스토어 조회 로직 구현

src/main/java/com/poppy/common/auth/handler/OAuth2LoginSuccessHandler.java
- 로그인 후 리다이렉트 주소 변경
- 없음
- 로그인 후 리다이렉트 주소 변경
<br>
=> [Fix]: 로그인 후 리다이렉트 주소 변경

src/main/java/com/poppy/common/exception/ErrorCode.java, src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreCalenderRspDto.java, src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java, src/main/java/com/poppy/domain/review/dto/response/PageMetadata.java, src/main/java/com/poppy/domain/review/dto/response/PageRspDto.java, src/main/java/com/poppy/domain/review/dto/response/ReviewRspDto.java, src/main/java/com/poppy/domain/user/dto/UserReservationRspDto.java, src/main/java/com/poppy/domain/waiting/dto/request/UpdateWaitingStatusReqDto.java, src/main/java/com/poppy/domain/waiting/dto/request/WaitingSettingsReqDto.java
- DTO 시간 반환 형식 변경
- 없음 (ex. 사용자가 글을 작성할 수 있게 함)
- String으로 출력되게 변경 (yyyy-MM-dd, HH:mm:ss)
<br>
=> [Refactor]: DTO 시간 반환 형식 변경

src/main/java/com/poppy/domain/popupStore/dto/request/PopupStoreReqDto.java, src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
- DTO 반환 시 description 추가
- 없음
- 없음
<br>
=> [Refactor]: DTO 반환 시 description 추가

src/main/java/com/poppy/domain/reservation/dto/ReservationRspDto.java, src/main/java/com/poppy/domain/reservation/service/ReservationService.java, src/main/java/com/poppy/domain/user/controller/UserController.java, src/main/java/com/poppy/domain/user/dto/response/UserReservationDetailRspDto.java, src/main/java/com/poppy/domain/user/dto/response/UserReservationRspDto.java, src/main/java/com/poppy/domain/user/service/UserService.java
- 예약 상세페이지 전달 DTO 수정
- 없음
- 없음
<br>
=> [Refactor]: 예약 상세페이지 전달 DTO 수정

src/main/java/com/poppy/common/util/LocalDateWithDayOfWeekSerializer.java, src/main/java/com/poppy/common/util/LocalTimeWithAmPmSerializer.java, src/main/java/com/poppy/domain/payment/controller/PaymentController.java, src/main/java/com/poppy/domain/payment/dto/ReservationPaymentRspDto.java, src/main/java/com/poppy/domain/popupStore/dto/request/PopupStoreReqDto.java, src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreCalenderRspDto.java, src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java, src/main/java/com/poppy/domain/reservation/controller/ReservationController.java, src/main/java/com/poppy/domain/reservation/dto/request/ReservationReqDto.java, src/main/java/com/poppy/domain/reservation/dto/response/ReservationRspDto.java, src/main/java/com/poppy/domain/review/dto/response/ReviewRspDto.java, src/main/java/com/poppy/domain/user/dto/response/UserReservationDetailRspDto.java, src/main/java/com/poppy/domain/user/dto/response/UserReservationRspDto.java, src/main/java/com/poppy/domain/waiting/dto/response/UserWaitingHistoryRspDto.java
- 날짜 및 시간 형식 지정
- 날짜 및 시간 Serializer 클래스 생성
- 날짜: yyyy-MM-dd (요일)
- 시간: 오전/오후 hh:mm
<br>
=> [Refactor]: 날짜 및 시간 형식 지정

src/test/java/com/poppy/domain/notice/service/NoticeServiceTest.java, src/test/java/com/poppy/domain/notification/service/NotificationServiceTest.java
- NoticeServiceTest 구현, NotificationServiceTest 추가
- 없음
- 없음
<br>
- [ ✅  ] 💯 테스트는 잘 통과했나요?
=> [Test]: NoticeServiceTest 구현, NotificationServiceTest 추가

src/main/java/com/poppy/common/config/security/SecurityConfig.java, src/main/java/com/poppy/common/exception/ErrorCode.java, src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java, src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java, src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java, src/main/java/com/poppy/domain/scrap/controller/ScrapController.java, src/main/java/com/poppy/domain/scrap/dto/ScrapRspDto.java, src/main/java/com/poppy/domain/scrap/dto/UserScrapRspDto.java, src/main/java/com/poppy/domain/scrap/entity/Scrap.java, src/main/java/com/poppy/domain/scrap/entity/ScrapSortType.java, src/main/java/com/poppy/domain/scrap/repository/ScrapRepository.java, src/main/java/com/poppy/domain/scrap/service/ScrapService.java, src/main/java/com/poppy/domain/user/entity/User.java
- 스크랩 기능 구현
- 팝업 스토어 스크랩
- 유저별 스크랩 목록 조회 및 삭제 구현
- 목록 정렬: 등록순, 오픈일순, 마감일순
- 팝업스토어 조회 시 스크랩 수도 조회하게 변경
<br>
=> [Feat]: 스크랩 기능 구현

src/main/java/com/poppy/domain/waiting/service/DistributedLockService.java, src/main/java/com/poppy/domain/waiting/service/WaitingScheduler.java, src/test/java/com/poppy/domain/waiting/service/WaitingSchedulerTest.java
- 스케줄러 알림 로직 분산 락 적용
- '호출 후 5분 이후 알림' 로직 분산 락 적용
- 테스트 코드 작성
- 없음
<br>
=> [Feat]: 스케줄러 알림 로직 분산 락 적용

src/main/java/com/poppy/common/exception/ErrorCode.java, src/main/java/com/poppy/domain/review/service/ReviewService.java
- ReviewLike 분산락 적용
- 에러코드(409, "잠시 후 다시 시도해 주세요.) 추가
- 없음
<br>
- [ ✅  ] 🏷️ 라벨은 등록했나요?
=> [Refactor]: ReviewLike 분산락 적용

src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java, src/main/java/com/poppy/domain/popupStore/dto/request/PopupStoreSearchReqDto.java, src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepositoryCustom.java, src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepositoryImpl.java, src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java, src/test/java/com/poppy/domain/popupstore/PopupStoreServiceTest.java
- 팝업스토어 검색 필터링 구현
- 없음
- location, date, category 각각 받던 거 삭제 후 하나로 합침
<br>
=> [Refactor]: 팝업스토어 검색 필터링 구현

build.gradle, src/main/java/com/poppy/common/aop/LoggingAspect.java, src/main/resources/logback-spring.xml
- 로깅 처리 구현
- AOP 활용하여 컨트롤러의 모든 메소드에 대한 실행 시간과 파라미터를 자동으로 로깅
- INFO와 ERROR 레벨을 분리하여 각각 다른 파일에 로그를 저장
- 없음
<br>
=> [Feat]: 로깅 처리 구현

src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
- PopupStoreRspDto 날짜 및 시간 형식 수정
- 내부 클래스 사용하여 날짜 반환 형식 분리
- 없음
<br>
=> [refactor]: PopupStoreRspDto 날짜 및 시간 형식 수정

build.gradle, src/main/java/com/poppy/common/config/redis/RedisConfig.java
- Redis connection pool 및 container 설정
- 없음 (ex. 사용자가 글을 작성할 수 있게 함)
- 없음
<br>
=> [Refactor]: Redis connection pool 및 container 설정

.gitignore, build.gradle, src/main/java/com/poppy/admin/controller/AdminController.java, src/main/java/com/poppy/admin/service/AdminService.java, src/main/java/com/poppy/common/config/multipart/MultipartConfig.java, src/main/java/com/poppy/common/config/s3/S3Config.java, src/main/java/com/poppy/common/entity/Images.java, src/main/java/com/poppy/common/exception/ErrorCode.java, src/main/java/com/poppy/common/repository/ImageRepository.java, src/main/java/com/poppy/common/service/ImageService.java, src/main/java/com/poppy/domain/popupStore/dto/request/PopupStoreReqDto.java, src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java, src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java, src/main/java/com/poppy/domain/popupStore/entity/PopupStoreView.java, src/main/java/com/poppy/domain/review/controller/ReviewController.java, src/main/java/com/poppy/domain/review/dto/request/ReviewReqDto.java, src/main/java/com/poppy/domain/review/dto/response/ReviewRspDto.java, src/main/java/com/poppy/domain/review/entity/Review.java, src/main/java/com/poppy/domain/review/service/ReviewService.java, src/main/java/com/poppy/domain/scrap/dto/UserScrapRspDto.java, src/main/java/com/poppy/domain/user/dto/response/UserReservationRspDto.java
- 리뷰, 팝업 스토어 관련 이미지 S3 처리
- 리뷰 등록, 수정, 삭제 시 이미지 처리
- 팝업 스토어 등록, 삭제 시 이미지 처리
- 썸네일은 이미지 목록 중 첫번째 요소
- 팝업 스토어 등록 시 categoryName 등록에서 categoryId로 수정
<br>
=> [Feat]: 리뷰, 팝업 스토어 관련 이미지 S3 처리

src/main/java/com/poppy/common/auth/controller/TestUserController.java
- 테스트 유저 생성 로직 변경
- 없음
- 닉네임 UUID로 설정
<br>
=> [Fix]: 테스트 유저 생성 로직 변경

src/test/java/com/poppy/domain/waiting/service/MasterWaitingServiceTest.java, src/test/java/com/poppy/domain/waiting/service/UserWaitingServiceTest.java
- MasterWaitingServiceTest, UserWaitingServiceTest 메소드 추가
- 없음
- 없음
<br>
- [ ✅  ] 💯 테스트는 잘 통과했나요?
=> [Test]: MasterWaitingServiceTest, UserWaitingServiceTest 메소드 추가

build.gradle, src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java, src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepository.java, src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
- 특정 구 내에 있는 팝업스토어 검색
- 없음
- 없음
<br>
=> [Feat]: 특정 구 내에 있는 팝업스토어 검색

src/main/java/com/poppy/domain/notice/dto/NoticeRspDto.java, src/main/java/com/poppy/domain/waiting/dto/response/WaitingRspDto.java, src/main/java/com/poppy/domain/waiting/entity/Waiting.java
- 웨이팅 알림 등록 시 날짜/시간 추가, 공지사항 조회 시 id 필드 추가
- 없음
- 없음
<br>
=> [Fix]: 웨이팅 알림 등록 날짜/시간 추가, 공지사항 조회 시 id 필드 추가

src/test/java/com/poppy/admin/service/AdminServiceTest.java, src/test/java/com/poppy/domain/popupstore/PopupStoreServiceTest.java, src/test/java/com/poppy/domain/review/service/ReviewServiceTest.java
- 이미지 관련 테스트 코드 수정
- 없음
- 리뷰, 팝업 스토어 관련 테스트 코드 수정
<br>
=> [Test]: 이미지 관련 테스트 코드 수정

src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java, src/main/java/com/poppy/domain/review/repository/ReviewRepository.java, src/main/java/com/poppy/domain/review/service/ReviewService.java
- 리뷰 변동시 연관된 팝업스토어의 평점 갱신
- 없음 (ex. 사용자가 글을 작성할 수 있게 함)
- 없음
<br>
=> [Feat]: 리뷰 변동시 연관된 팝업스토어의 평점 갱신

src/main/java/com/poppy/common/service/ImageService.java, src/main/java/com/poppy/domain/notification/dto/ReservationNotificationDto.java, src/main/java/com/poppy/domain/notification/dto/WaitingNotificationDto.java, src/main/java/com/poppy/domain/notification/entity/NotificationType.java, src/main/java/com/poppy/domain/notification/service/NotificationMessageGenerator.java, src/main/java/com/poppy/domain/notification/service/NotificationService.java, src/main/java/com/poppy/domain/payment/repository/PaymentRepository.java, src/main/java/com/poppy/domain/reservation/entity/Reservation.java, src/main/java/com/poppy/domain/reservation/service/ReservationService.java, src/main/java/com/poppy/domain/user/dto/response/UserReservationDetailRspDto.java, src/main/java/com/poppy/domain/user/dto/response/UserReservationRspDto.java, src/test/java/com/poppy/domain/notification/service/NotificationServiceTest.java
- 예약 취소 알림 구현
- 예약 목록 반환 시 popupStoreId 추가
- imageService 필요없는 로그 삭제
- 알림 타입 예약 완료/취소 구분
- 예약 알림 전송 시 날짜와 시간 반환
- 예약 시 취소 타입인 경우 업데이트
<br>
=> [Refactor]: 예약 취소 알림 구현

src/main/java/com/poppy/common/auth/JwtTokenizer.java, src/main/java/com/poppy/common/auth/dto/TokenRspDto.java
- 로그인 시 유저 닉네임 반환
- 없음
- 없음
<br>
=> [Refactor]: 로그인 시 유저 닉네임 반환

src/main/java/com/poppy/common/auth/cache/OAuthOTUCache.java, src/main/java/com/poppy/common/config/security/SecurityConfig.java
- CORS 설정 수정
- 없음
- 일회용 인증 코드 기간 10분으로 수정
<br>
=> [Fix]: CORS 설정 수정

src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
- 팝업 스토어 반환 시 조회 수 추가
- 없음
- 없음
<br>
=> [Refactor]: 팝업 스토어 반환 시 조회 수 추가

src/main/java/com/poppy/common/exception/ErrorCode.java, src/main/java/com/poppy/domain/user/controller/UserController.java, src/main/java/com/poppy/domain/user/entity/User.java, src/main/java/com/poppy/domain/user/service/UserService.java
- 회원 탈퇴 구현
- 일반 유저만 탈퇴 가능
- 없음
<br>
=> [Feat]: 회원 탈퇴 구현

src/main/java/com/poppy/admin/service/AsyncRedisSlotInitializationService.java, src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
- 팝업 스토어 등록 로직 에러 해결
- 없음 (ex. 사용자가 글을 작성할 수 있게 함)
- Redis 슬롯 기한 1년으로 변경
- 리뷰 수 반환 못하던 문제 해결
<br>
=> [Fix]: 팝업 스토어 등록 로직 에러 해결

src/main/java/com/poppy/PoppyApplication.java, src/main/java/com/poppy/common/config/security/SecurityConfig.java, src/main/java/com/poppy/domain/search/controller/SearchHistoryController.java, src/main/java/com/poppy/domain/search/service/HourlyKeywordScheduler.java, src/main/java/com/poppy/domain/search/service/PopularKeywordService.java, src/main/java/com/poppy/domain/search/service/StoreSearchService.java
- 인기 검색어 조회 구현
- 1시간마다 인기 검색어 업데이트
- Redis에서 횟수가 많은 10개를 기준으로 조회
- 없음
<br>
=> [Feat]: 인기 검색어 조회 구현

src/main/java/com/poppy/common/config/redis/DistributedLockService.java, src/main/java/com/poppy/domain/notification/dto/ScrapedStoreNotificationDto.java, src/main/java/com/poppy/domain/notification/entity/NotificationType.java, src/main/java/com/poppy/domain/notification/service/NotificationMessageGenerator.java, src/main/java/com/poppy/domain/notification/service/NotificationService.java, src/main/java/com/poppy/domain/scrap/repository/ScrapRepository.java, src/main/java/com/poppy/domain/scrap/service/ScrapOpeningNotificationScheduler.java
- 저장해놓은 팝업스토어 오픈일이 되면 알림 전송 구현
- 없음
- 없음
<br>
=> [Feat]: 저장해놓은 팝업스토어 오픈일이 되면 알림 전송 구현

src/main/java/com/poppy/common/exception/ErrorCode.java, src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java, src/main/java/com/poppy/domain/popupStore/dto/request/PopupStoreUpdateReqDto.java, src/main/java/com/poppy/domain/popupStore/entity/PopupStore.java, src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java, src/main/java/com/poppy/domain/reservation/repository/ReservationAvailableSlotRepository.java, src/main/java/com/poppy/domain/reservation/repository/ReservationRepository.java
=> [Feat]: 팝업스토어 수정

src/main/java/com/poppy/common/config/security/SecurityConfig.java, src/main/java/com/poppy/domain/popupStore/entity/PopupStoreView.java, src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java, src/main/java/com/poppy/domain/user/controller/UserController.java, src/main/java/com/poppy/domain/user/dto/response/UserPopupStoreRspDto.java, src/main/java/com/poppy/domain/user/repository/LoginUserProvider.java, src/main/java/com/poppy/domain/user/repository/LoginUserProviderImpl.java, src/main/java/com/poppy/domain/user/repository/UserRepository.java, src/main/java/com/poppy/domain/user/repository/UserRepositoryCustom.java, src/main/java/com/poppy/domain/user/repository/UserRepositoryCustomImpl.java, src/main/java/com/poppy/domain/user/service/UserService.java
- 유저별 최근 본 팝업 스토어 조회
- 유저 별로 최근 본 팝업 스토어 10개 조회
- 없음
<br>
=> [Feat]: 유저별 최근 본 팝업 스토어 조회

src/main/java/com/poppy/common/auth/JwtTokenizer.java, src/main/java/com/poppy/common/auth/dto/TokenRspDto.java
- 로그인 유저 반환 시 핸드폰 번호도 반환하도록 변경
- 없음
- 없음
<br>
=> [Refactor]: 로그인 유저 반환 시 핸드폰 번호도 반환하도록 변경

src/main/java/com/poppy/domain/reservation/dto/response/ReservationRspDto.java
- 예약 완료 시 reservationId 반환 추가
- 없음
- 없음
<br>
=> [Refactor]: 예약 완료 시 reservationId 반환 추가

src/main/java/com/poppy/domain/user/controller/UserController.java
- 예약 내역 조회 url 변경
- 없음
- 없음
<br>
=> [Refactor]: 예약 내역 조회 url 변경

src/main/java/com/poppy/domain/scrap/service/ScrapService.java
- ScrapCount 반환 오류 수정
- 없음
- 없음
<br>
=> [fix]: ScrapCount 반환 오류 수정

src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java, src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java, src/main/java/com/poppy/domain/review/controller/ReviewController.java, src/main/java/com/poppy/domain/review/dto/response/ReviewRspDto.java, src/main/java/com/poppy/domain/review/service/ReviewService.java, src/main/java/com/poppy/domain/scrap/controller/ScrapController.java, src/main/java/com/poppy/domain/scrap/repository/ScrapRepository.java, src/main/java/com/poppy/domain/scrap/service/ScrapService.java
- 스크랩 토글 안 되던 문제 해결
- 리뷰 조회 시 좋아요 여부 반환
- 스크랩 삭제 API 삭제
- 리뷰 상세 조회 삭제
<br>
=> [Fix]: 스크랩 토글 안 되던 문제 해결

src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java, src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepositoryCustom.java, src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepositoryImpl.java, src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
- 비슷한 팝업 추천 로직 구현
- 상세 조회 팝업 스토어와 카테고리가 같은 팝업 스토어 랜덤 5개 반환
- 없음
<br>
=> [Feat]: 비슷한 팝업 추천 로직 구현

src/main/java/com/poppy/domain/popupStore/dto/response/PopupStoreRspDto.java
- 리뷰 개수 조회 문제 해결
- 없음
- 없음
<br>
=> [Fix]: 리뷰 개수 조회 문제 해결

src/main/java/com/poppy/domain/popupStore/controller/PopupStoreController.java, src/main/java/com/poppy/domain/popupStore/repository/PopupStoreRepository.java, src/main/java/com/poppy/domain/popupStore/service/PopupStoreService.java
- 마감이 임박한 팝업스토어 list 반환
- 없음 
- 없음
<br>
- [ ✅  ] 💯 테스트는 잘 통과했나요?
- [ ✅  ] 🏗️ 빌드는 성공했나요?
- [ ✅  ] 🧹 불필요한 코드는 제거했나요?
- [ ✅  ] 💭 이슈는 등록했나요?
- [ ✅  ] 🏷️ 라벨은 등록했나요?
=> [Feat]: 마감이 임박한 팝업스토어 list 반환

src/main/java/com/poppy/domain/waiting/service/UserWaitingService.java
- 팝업 스토어 운영 시간 확인 로직 변경
- 없음
- 시간을 분까지만 비교하도록 변경
<br>
=> [Fix]: 팝업 스토어 운영 시간 확인 로직 변경

src/main/java/com/poppy/domain/waiting/controller/UserWaitingController.java, src/main/java/com/poppy/domain/waiting/service/UserWaitingService.java, src/test/java/com/poppy/domain/waiting/service/UserWaitingServiceTest.java
- 현재 시간 확인 로그 추가
- 없음
- 없음
<br>
=> [Chore]: 현재 시간 확인 로그 추가

src/main/java/com/poppy/domain/user/dto/response/UserReservationRspDto.java
- reservation 반환시 reservationId 함께 반환하도록 수정
- 없음 
- 없음
<br>
=> [fix]: reservation 반환시 reservationId 함께 반환하도록 수정

src/main/java/com/poppy/domain/waiting/dto/response/UserWaitingHistoryRspDto.java
- UserWaitingHistoryRspDto 썸네일 추가 #27
- 없음
- 없음
<br>
=> [Fix]: UserWaitingHistoryRspDto 썸네일 추가

src/main/java/com/poppy/domain/user/dto/response/UserReservationRspDto.java, src/main/java/com/poppy/domain/waiting/dto/response/UserWaitingHistoryRspDto.java
=> [Fix]: dto 필드 수정

src/main/java/com/poppy/domain/waiting/dto/response/UserWaitingHistoryRspDto.java
=> [Fix]: dto 필드 추가

src/main/java/com/poppy/common/auth/JwtTokenizer.java, src/main/java/com/poppy/common/auth/dto/TokenRspDto.java
- 로그인/회원가입 시 userId 반환
- 없음
- 없음
<br>
=> [Refactor]: 로그인/회원가입 시 userId 반환

src/main/java/com/poppy/domain/scrap/controller/ScrapController.java, src/main/java/com/poppy/domain/scrap/dto/UserScrapRspDto.java, src/main/java/com/poppy/domain/scrap/service/ScrapService.java
- 유저 스크랩 조회 반환 변경
- 스크랩 삭제 로직 추가
- 없음
<br>
=> [Refactor]: 유저 스크랩 조회 반환 변경

src/main/java/com/poppy/domain/review/repository/ReviewRepository.java, src/main/java/com/poppy/domain/review/service/ReviewService.java, src/main/java/com/poppy/domain/user/controller/UserController.java, src/main/java/com/poppy/domain/user/dto/response/UserReviewRspDto.java
- 유저별 리뷰 조회 로직 구현
- 없음
- 없음
<br>
=> [Feat]: 유저별 리뷰 조회 로직 구현

src/main/java/com/poppy/domain/scrap/controller/ScrapController.java, src/main/java/com/poppy/domain/scrap/dto/request/UserScrapReqDto.java, src/main/java/com/poppy/domain/scrap/dto/response/ScrapRspDto.java, src/main/java/com/poppy/domain/scrap/dto/response/UserScrapRspDto.java, src/main/java/com/poppy/domain/scrap/repository/ScrapRepository.java, src/main/java/com/poppy/domain/scrap/service/ScrapService.java
- 스크랩 삭제 여러 개 가능하도록 수정
- 없음
- 없음
<br>
=> [Refactor]: 스크랩 삭제 여러 개 가능하도록 수정

src/main/java/com/poppy/domain/notification/dto/NoticeNotificationDto.java, src/main/java/com/poppy/domain/notification/dto/ReservationNotificationDto.java, src/main/java/com/poppy/domain/notification/service/NotificationMessageGenerator.java, src/main/java/com/poppy/domain/notification/service/NotificationService.java, src/test/java/com/poppy/domain/notification/service/NotificationServiceTest.java
- websocket 메시지 형식 수정 및 dto 필드(날짜, 시간) 추가
<br>
=> [Fix]: websocket 메시지 형식 수정 및 dto 필드(날짜, 시간) 추가

src/main/java/com/poppy/domain/review/controller/ReviewController.java, src/main/java/com/poppy/domain/review/service/ReviewService.java
=> [Feat]: 리뷰 상세 조회 구현

src/main/java/com/poppy/domain/notification/dto/WaitingNotificationDto.java
- WaitingNotificationDto 필드(날짜, 시간) 추가
- 없음
- 없음
<br>
=> [Fix]: WaitingNotificationDto 필드(날짜, 시간) 추가

src/main/java/com/poppy/domain/review/dto/request/ReviewReqDto.java, src/main/java/com/poppy/domain/review/dto/response/ReviewRspDto.java, src/main/java/com/poppy/domain/review/entity/Review.java, src/main/java/com/poppy/domain/review/service/ReviewService.java
- 리뷰 수정 시 기존 이미지 삭제되는 문제 해결
- 없음
- 리뷰 등록 시 지울 이미지 선택 추가
- 리뷰 조회 시 imageId 목록 추가
<br>
=> [Fix]: 리뷰 수정 시 기존 이미지 삭제되는 문제 해결

src/main/java/com/poppy/domain/user/dto/response/UserReviewRspDto.java
- review 반환시 이미지 업로드 Url, location 추가
- 없음
- 없음
<br>
=> [fix]: review 반환시 이미지 업로드 Url, location 추가

src/main/java/com/poppy/domain/scrap/dto/response/UserScrapRspDto.java
- thumbnail 필드명 변경
- 없음
- thumbnail에서 thumbnailUrl로 변경
<br>
=> [Chore]: thumbnail 필드명 변경

src/main/java/com/poppy/domain/scrap/dto/response/UserScrapRspDto.java
- popupStoreId 필드명 변경
- 없음
- 없음
<br>
=> [Chore]: popupStoreId 필드명 변경

src/main/java/com/poppy/common/config/redis/NotificationSubscriber.java, src/main/java/com/poppy/common/config/websocket/WebSocketConfig.java
- WebSocket 경로 변경
- 없음
- 없음
<br>
=> [Fix]: WebSocket 경로 변경

src/main/java/com/poppy/common/config/websocket/WebSocketConfig.java
- WebSocketConfig 수정
- 없음
- 없음
<br>
=> [Fix]: WebSocketConfig 수정

src/main/java/com/poppy/common/config/redis/NotificationSubscriber.java
- 공지사항 WebSocket 알림 경로 추가
- 없음
- 없음
<br>
=> [Feat]: 공지사항 WebSocket 알림 경로 추가
